### ISSUE TITLE
Your Tools is fantastic !

### ISSUE THREAD

**Issue by Snipy44** [MaxLastBreath/TOTK-mods#37] opened 2023-11-06 02:14 UTC
Your Tools is fantastic ! But is possible to have this also for BOTW Yuzu/Ryujinx ? <3

**Comment by MaxLastBreath** [comment] 2023-11-06 13:38
Thank you! Sadly BOTW doesn't have that many mods for Yuzu/Ryujinx that are essential as most of the botw mods are in CEMU And already mostly built in :(

**Comment by MaxLastBreath** [comment] 2023-11-06 16:12
Would take too long time, porting every single mod, you should try cemu for botw, it runs twice as better as on yuzu and ryujinx.

**Comment by Snipy44** [comment] 2023-11-06 16:13
yes i know, and i have this, but i want play on switch emulator ^^'

**Comment by MaxLastBreath** [comment] 2024-11-30 17:05
Duplicate of #96

**Closed by MaxLastBreath** 2024-11-30 17:05 UTC
